import 'dart:convert';

import '../utils/platform_util.dart';
import 'dart:isolate';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_explode;
import 'storage_service.dart';
import 'cobalt_service.dart';
import 'youtube_resolution_queue.dart';
import 'youtube_stream_probe.dart';

/// A YouTube video surfaced from a search.
class YoutubeVideo {
  final String id;
  final String title;
  final String author;
  final String? thumbnailUrl;
  final int? durationSeconds;
  final int? views;

  /// Relative published label as YouTube returns it, e.g. "6 years ago".
  final String? publishedLabel;

  const YoutubeVideo({
    required this.id,
    required this.title,
    required this.author,
    this.thumbnailUrl,
    this.durationSeconds,
    this.views,
    this.publishedLabel,
  });

  /// Format views for display (e.g., 1.2M, 676K).
  String get formattedViews {
    final v = views;
    if (v == null || v < 0) return '';
    if (v >= 1000000) return '${(v / 1000000).toStringAsFixed(1)}M views';
    if (v >= 1000) return '${(v / 1000).toStringAsFixed(1)}K views';
    return '$v views';
  }
}

/// Result of a YouTube search request.
class YoutubeSearchResult {
  final List<YoutubeVideo> videos;
  final bool hasMore;

  const YoutubeSearchResult({required this.videos, this.hasMore = false});
}

/// One selectable video quality (a video-only track). All qualities of a
/// video share the same separate [YoutubeResolvedStreams.audioUrl], so switching
/// quality only swaps the video URL — the player re-muxes the same audio.
///
/// Entries are capped at 1080p. AV1 is excluded for decoder compatibility.
/// One closed-caption / subtitle track offered by YouTube for a video.
///
/// [url] is a direct WebVTT URL (YouTube's timedtext endpoint requested with
/// `fmt=vtt`), so it feeds the player's existing external-subtitle pipeline
/// unchanged. [langName] is YouTube's own human label (e.g. "English (auto-
/// generated)"); [langCode] is the BCP-47/ISO code used for language matching.
class YoutubeCaptionTrack {
  final String url;
  final String langCode;
  final String langName;
  final bool isAutoGenerated;
  const YoutubeCaptionTrack({
    required this.url,
    required this.langCode,
    required this.langName,
    this.isAutoGenerated = false,
  });
}

class YoutubeQuality {
  final int height;
  final String videoUrl;
  const YoutubeQuality({required this.height, required this.videoUrl});

  String get label => '${height}p';
}

/// Resolved playable/downloadable URLs for a single YouTube video.
class YoutubeResolvedStreams {
  /// Video stream to play. When [audioUrl] is set this is a *video-only*
  /// adaptive stream (always H.264, capped at the user's preferred height) and
  /// the player must mux in [audioUrl]; otherwise it is a muxed (audio+video)
  /// progressive stream. Playback and [qualities] are capped at 1080p.
  final String? playUrl;

  /// Separate audio track to play alongside a video-only [playUrl]. Null when
  /// [playUrl] is already muxed.
  final String? audioUrl;

  /// Single-file (muxed) stream for downloads — has audio, but caps at ~360p.
  final String? downloadUrl;

  /// Pixel height of [downloadUrl] (e.g. 720, 360), for surfacing the actual
  /// download quality to the user. Null if it couldn't be determined.
  final int? downloadHeight;

  /// Whether [downloadUrl] carries audio. True for a muxed stream (the normal
  /// case); false only in the rare fallback where the sole available stream is
  /// a video-only track (YouTube served no combined file for this video).
  final bool downloadHasAudio;

  final String? title;
  final String? thumbnailUrl;
  final int? durationSeconds;

  /// All video-only qualities available (highest first), for in-player quality
  /// switching. H.264 or VP9 up to 1080p; AV1 excluded.
  /// Populated only in the separate-audio path (each entry pairs with the shared
  /// [audioUrl]); empty when only a muxed stream exists.
  final List<YoutubeQuality> qualities;

  /// Closed-caption tracks (one per language), as direct WebVTT URLs. Empty
  /// when the video has no captions. Best-effort: a caption-fetch failure never
  /// blocks playback.
  final List<YoutubeCaptionTrack> captions;

  /// Public relay URLs can expire much sooner than direct signed streams.
  final DateTime? validUntil;

  /// [playUrl] is a Cobalt tunnel: a live, muxed remux with no byte-range
  /// support that can only be (re)opened until [validUntil]. Seeks and loop
  /// restarts on it are best-effort; a failed relay is retried directly.
  final bool isRelay;

  const YoutubeResolvedStreams({
    this.playUrl,
    this.audioUrl,
    this.downloadUrl,
    this.downloadHeight,
    this.downloadHasAudio = true,
    this.title,
    this.thumbnailUrl,
    this.durationSeconds,
    this.qualities = const [],
    this.captions = const [],
    this.validUntil,
    this.isRelay = false,
  });

  bool get hasPlayable => playUrl != null && playUrl!.isNotEmpty;

  /// Short-lived relays preloaded for a later reel need refreshing before use.
  bool get needsRefresh {
    final now = DateTime.now();
    if (validUntil?.isAfter(now) == false) return true;
    for (final url in [playUrl, audioUrl]) {
      final query = Uri.tryParse(url ?? '')?.queryParameters;
      final millis = int.tryParse(query?['exp'] ?? '');
      final seconds = int.tryParse(query?['expire'] ?? '');
      final expiry = millis ?? (seconds == null ? null : seconds * 1000);
      if (expiry != null && expiry <= now.millisecondsSinceEpoch + 30000) {
        return true;
      }
    }
    return false;
  }

  /// Pixel height of the URL selected for playback, when the manifest reports
  /// it. A null result means the source did not identify its selected format;
  /// callers should treat that as unknown rather than assuming it is low-res.
  int? get playbackHeight {
    final url = playUrl;
    if (url == null) return null;
    for (final quality in qualities) {
      if (quality.videoUrl == url) return quality.height;
    }
    return url == downloadUrl ? downloadHeight : null;
  }

  /// A single-file playback fallback only when it is known to contain audio.
  /// [downloadUrl] itself may still be video-only in the rare no-muxed-stream
  /// case so downloads can retain their existing best-effort behavior.
  ///
  /// Null for a relay: this is the URL handed to AVFoundation (the iOS
  /// platform-view trailer player), which only opens byte-range-capable
  /// files. Without it the backdrop plays the muxed tunnel through
  /// media_kit, which streams it fine.
  String? get muxedPlaybackFallback =>
      downloadHasAudio && !isRelay ? downloadUrl : null;
}

/// A resolved-streams cache entry with the time it was resolved (for TTL).
class _ResolvedCacheEntry {
  final YoutubeResolvedStreams streams;
  final DateTime at;

  /// Earlier cut-off than the usual TTL (a provisional fallback).
  final DateTime? until;
  const _ResolvedCacheEntry(this.streams, this.at, {this.until});
}

/// One client rung's chosen streams, pre-probe (see the client ladder in
/// [YoutubeService._resolveStreamsBlocking]).
class _StreamSelection {
  final String playUrl;
  final String? audioUrl;
  final List<YoutubeQuality> qualities;
  final String? bestMuxedUrl;
  final int? bestMuxedHeight;
  const _StreamSelection({
    required this.playUrl,
    required this.audioUrl,
    required this.qualities,
    required this.bestMuxedUrl,
    required this.bestMuxedHeight,
  });

  int? get playbackHeight {
    for (final quality in qualities) {
      if (quality.videoUrl == playUrl) return quality.height;
    }
    return bestMuxedHeight;
  }

  _StreamSelection withoutMuxedFallback() => _StreamSelection(
    playUrl: playUrl,
    audioUrl: audioUrl,
    qualities: qualities,
    bestMuxedUrl: null,
    bestMuxedHeight: null,
  );
}

/// Service for searching and resolving YouTube videos fully on-device.
///
/// - **Search** uses YouTube's internal InnerTube API directly (the same
///   endpoint the website uses). youtube_explode's own search parser is broken
///   in the current release, and public Piped/Invidious search proxies are
///   unreliable, so we call InnerTube ourselves with a parser we control.
/// - **Resolution** uses youtube_explode's stream extraction, which runs
///   against YouTube from the user's own IP — this avoids the "confirm you're
///   not a bot" datacenter-IP blocks that break public proxy instances.
///
/// No API key to manage and no third-party server in the path.
///
/// Shared: [LemmyService] uses [extractYouTubeId] + [resolveStreams] to make
/// Lemmy's many YouTube links playable in-app.
class YoutubeService {
  static const String _userAgent =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

  // Public InnerTube web-client key + context (well-known constants).
  static const String _innertubeKey = 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8';
  static const String _clientName = 'WEB';
  static const String _clientVersion = '2.20240101.00.00';
  static const Duration _httpTimeout = Duration(seconds: 15);

  /// Continuation token for the current search (for pagination).
  static String? _continuationToken;

  // ============== Search (InnerTube) ==============

  static Map<String, dynamic> get _context => {
    'client': {
      'clientName': _clientName,
      'clientVersion': _clientVersion,
      'hl': 'en',
      'gl': 'US',
    },
  };

  static Future<Map<String, dynamic>> _innertube(
    String endpoint,
    Map<String, dynamic> body,
  ) async {
    final uri = Uri.parse(
      'https://www.youtube.com/youtubei/v1/$endpoint?key=$_innertubeKey&prettyPrint=false',
    );
    final resp = await http
        .post(
          uri,
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': _userAgent,
          },
          body: json.encode({'context': _context, ...body}),
        )
        .timeout(_httpTimeout);

    if (resp.statusCode != 200) {
      throw Exception('YouTube search failed (HTTP ${resp.statusCode})');
    }
    return json.decode(resp.body) as Map<String, dynamic>;
  }

  /// Run a fresh search. Resets pagination state.
  static Future<YoutubeSearchResult> search(String query) async {
    final data = await _innertube('search', {'query': query});
    return _parseSearchResponse(data);
  }

  /// Fetch the next page of the current search, if any.
  static Future<YoutubeSearchResult> searchMore() async {
    final token = _continuationToken;
    if (token == null || token.isEmpty) {
      return const YoutubeSearchResult(videos: [], hasMore: false);
    }
    final data = await _innertube('search', {'continuation': token});
    return _parseSearchResponse(data);
  }

  static YoutubeSearchResult _parseSearchResponse(Map<String, dynamic> data) {
    final renderers = <Map<String, dynamic>>[];
    String? continuation;

    void walk(dynamic node) {
      if (node is Map<String, dynamic>) {
        final vr = node['videoRenderer'];
        if (vr is Map<String, dynamic>) renderers.add(vr);
        // The results "load more" token lives specifically in the
        // continuationItemRenderer — other continuationCommands in the
        // response belong to unrelated UI chrome (filters, topbar, hotkeys).
        final contItem = node['continuationItemRenderer'];
        if (contItem is Map) {
          final token =
              contItem['continuationEndpoint']?['continuationCommand']?['token'];
          if (token is String) continuation = token;
        }
        for (final v in node.values) {
          walk(v);
        }
      } else if (node is List) {
        for (final v in node) {
          walk(v);
        }
      }
    }

    walk(data);
    _continuationToken = continuation;

    final videos = <YoutubeVideo>[];
    for (final vr in renderers) {
      final video = _parseVideoRenderer(vr);
      if (video != null) videos.add(video);
    }

    return YoutubeSearchResult(
      videos: videos,
      hasMore: continuation != null && continuation!.isNotEmpty,
    );
  }

  static YoutubeVideo? _parseVideoRenderer(Map<String, dynamic> vr) {
    final id = vr['videoId']?.toString();
    if (id == null || id.isEmpty) return null;

    final title = _readText(vr['title']);
    if (title == null || title.isEmpty) return null;

    final author =
        _readText(vr['ownerText']) ?? _readText(vr['longBylineText']) ?? '';
    final lengthText = vr['lengthText']?['simpleText']?.toString();
    final viewsText =
        vr['viewCountText']?['simpleText']?.toString() ??
        _readText(vr['viewCountText']);
    final published = vr['publishedTimeText']?['simpleText']?.toString();

    return YoutubeVideo(
      id: id,
      title: title,
      author: author,
      thumbnailUrl: thumbnailForId(id),
      durationSeconds: _parseDuration(lengthText),
      views: _parseViews(viewsText),
      publishedLabel: published,
    );
  }

  /// Read a YouTube text object (`{simpleText}` or `{runs:[{text}]}`).
  static String? _readText(dynamic node) {
    if (node is! Map) return null;
    final simple = node['simpleText'];
    if (simple is String) return simple;
    final runs = node['runs'];
    if (runs is List) {
      return runs
          .map((r) => r is Map ? (r['text']?.toString() ?? '') : '')
          .join();
    }
    return null;
  }

  /// Parse "1:01:14" / "6:10" into seconds.
  static int? _parseDuration(String? s) {
    if (s == null || s.isEmpty) return null;
    final parts = s.split(':');
    int secs = 0;
    for (final p in parts) {
      final n = int.tryParse(p.trim());
      if (n == null) return null;
      secs = secs * 60 + n;
    }
    return secs > 0 ? secs : null;
  }

  /// Parse "133,864,158 views" into an int.
  static int? _parseViews(String? s) {
    if (s == null) return null;
    final digits = s.replaceAll(RegExp(r'[^0-9]'), '');
    return digits.isEmpty ? null : int.tryParse(digits);
  }

  // ============== Stream resolution (youtube_explode) ==============

  /// Short-lived cache of successful resolves, keyed by videoId. googlevideo
  /// stream URLs stay valid far longer than this TTL, so a hit is safe to play —
  /// and it spares a second isolate + extraction when the detail page's trailer
  /// prefetch and its Trailer button (or a re-open) resolve the same id.
  static final Map<String, _ResolvedCacheEntry> _resolveCache = {};
  static final Map<String, int> _resolveGeneration = {};
  static String? _preferredClient;
  static YoutubeResolutionQueue _resolutionQueue = YoutubeResolutionQueue();

  @visibleForTesting
  static Future<({YoutubeResolvedStreams streams, String client})?> Function(
    String videoId,
    int maxHeight,
    bool withCaptions,
    bool preferVp9,
    bool includeMetadata,
    bool preferMuxed,
    String? preferredClient,
  )?
  streamResolverOverride;

  @visibleForTesting
  static Future<CobaltMedia?> Function(String videoId, int maxHeight)?
  cobaltResolverOverride;

  /// Relay URL → video id, so a player failure on an already-pruned (expired)
  /// relay entry can still be traced back to its video.
  static final Map<String, String> _relayUrlIds = {};

  /// Videos whose relay stream failed in a player: resolve them directly
  /// (seekable, loopable signed URLs) for a while instead of re-relaying.
  static final Map<String, DateTime> _relayBypassUntil = {};
  static const Duration _relayBypassTtl = Duration(minutes: 30);

  static bool _relayBypassed(String videoId) {
    final until = _relayBypassUntil[videoId];
    if (until == null) return false;
    if (until.isAfter(DateTime.now())) return true;
    _relayBypassUntil.remove(videoId);
    return false;
  }

  /// A relay stream for [videoId] failed to play: drop it and resolve the
  /// video through direct extraction from now on.
  static void markRelayFailed(String videoId) {
    _relayBypassUntil[videoId] = DateTime.now().add(_relayBypassTtl);
    while (_relayBypassUntil.length > 256) {
      _relayBypassUntil.remove(_relayBypassUntil.keys.first);
    }
    invalidateStreams(videoId);
  }

  @visibleForTesting
  static void resetResolutionForTesting() {
    _resolveCache.clear();
    _resolveInFlight.clear();
    _resolveGeneration.clear();
    _preferredClient = null;
    _resolutionQueue = YoutubeResolutionQueue();
    _relayUrlIds.clear();
    _relayBypassUntil.clear();
    streamResolverOverride = null;
    cobaltResolverOverride = null;
  }

  /// Discard failed signed URLs, including pending results from before retry.
  static void invalidateStreams(String videoId) {
    _resolveGeneration[videoId] = (_resolveGeneration[videoId] ?? 0) + 1;
    bool matches(String key) => key == videoId || key.startsWith('$videoId#');
    _resolveCache.removeWhere((key, _) => matches(key));
    _resolveInFlight.removeWhere((key, _) => matches(key));
  }

  /// A failed player should not receive the same cached signed URL on reopen.
  static void invalidateStreamUrl(String? url) {
    if (url == null) return;
    final relayId = _relayUrlIds.remove(url);
    if (relayId != null) markRelayFailed(relayId);
    final ids = <String>{};
    for (final entry in _resolveCache.entries) {
      final streams = entry.value.streams;
      if ([
        streams.playUrl,
        streams.audioUrl,
        streams.downloadUrl,
        ...streams.qualities.map((quality) => quality.videoUrl),
      ].contains(url)) {
        final id = entry.key.split('#').first;
        if (streams.isRelay) {
          _relayBypassUntil[id] = DateTime.now().add(_relayBypassTtl);
        }
        ids.add(id);
      }
    }
    for (final id in ids) {
      invalidateStreams(id);
    }
  }

  /// Reels and trailers already have title metadata. Return playable streams
  /// without fetching it again; native iOS uses a single muxed connection.
  ///
  /// Previews try the Cobalt relay first on every platform; see
  /// [resolveStreams]' `allowRelay`. A relay is a muxed live remux without
  /// byte ranges, so it is never offered as [muxedPlaybackFallback]
  /// (AVFoundation) and plays through media_kit/mpv or ExoPlayer instead.
  static Future<YoutubeResolvedStreams?> resolvePreviewStreams(
    String videoId, {
    int? maxHeightOverride,
    bool preferVp9 = false,
    bool? preferMuxed,
    bool? allowRelay,
  }) => resolveStreams(
    videoId,
    maxHeightOverride: maxHeightOverride ?? ambientTrailerMaxHeight,
    preferVp9: preferVp9,
    includeMetadata: false,
    preferMuxed: preferMuxed ?? PlatformUtil.isIosMobile,
    allowRelay: allowRelay,
  );

  static const Duration _resolveCacheTtl = Duration(minutes: 10);

  static bool _cacheUsable(_ResolvedCacheEntry entry) {
    final now = DateTime.now();
    if (entry.streams.validUntil?.isAfter(now) == false) return false;
    if (entry.until?.isAfter(now) == false) return false;
    if (now.difference(entry.at) >= _resolveCacheTtl) return false;
    for (final url in [
      entry.streams.playUrl,
      entry.streams.audioUrl,
      entry.streams.downloadUrl,
    ]) {
      if (url == null) continue;
      final query = Uri.tryParse(url)?.queryParameters;
      final relayExpires = int.tryParse(query?['exp'] ?? '');
      if (relayExpires != null &&
          relayExpires <= now.millisecondsSinceEpoch + 30000) {
        return false;
      }
      final expires = int.tryParse(query?['expire'] ?? '');
      if (expires != null &&
          expires * 1000 <= now.millisecondsSinceEpoch + 30000) {
        return false;
      }
    }
    return true;
  }

  /// Resolves in flight, keyed by videoId, so concurrent callers for the same id
  /// (prefetch + Trailer button) share one isolate instead of spawning two.
  static final Map<String, Future<YoutubeResolvedStreams?>> _resolveInFlight =
      {};

  /// Background playback uses 720p on iOS mobile; other devices use 1080p.
  static int get ambientTrailerMaxHeight =>
      PlatformUtil.isIosMobile ? 720 : 1080;

  /// Resolve a YouTube [videoId] into playable/downloadable stream URLs.
  ///
  /// For playback this prefers a high-res *video-only* H.264 stream at or below
  /// the user's preferred resolution (see [StorageService.getYoutubeMaxHeight])
  /// paired with a separate AAC audio stream (the player muxes them). For
  /// downloads it returns the best muxed single-file stream (has audio, ~360p).
  ///
  /// Deduped by in-flight id + cached briefly; the heavy extraction runs off the
  /// main isolate (see [_resolveStreamsBlocking]).
  /// [maxHeightOverride] forces the default-quality cap instead of the user's
  /// playback preference — the ambient hero/Discover trailers pass a low value
  /// (they render in a small region, so a 480p decode is plenty and far lighter
  /// on weak TV silicon: less decode, less buffering, less per-frame GPU upload).
  /// Cached separately from the un-capped resolve so it never collides with the
  /// fullscreen player resolving the same video at full quality.
  /// [withCaptions] additionally fetches the closed-caption manifest. Off by
  /// default so ambient/trailer/detail resolves (which never show subtitles)
  /// don't pay for an extra network round-trip; only the full playback path
  /// opts in. Keyed separately in the cache so a caption-less ambient resolve
  /// can't satisfy a later playback resolve of the same video (and vice versa).
  static Future<YoutubeResolvedStreams?> resolveStreams(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool preferVp9 = false,
    bool includeMetadata = true,
    bool preferMuxed = false,
    bool? allowRelay,
  }) {
    // Key the effective preference, so changing playback quality does not
    // reuse a lower-resolution result cached under a preference-free key.
    if (maxHeightOverride == null) {
      return StorageService.getYoutubeMaxHeight().then(
        (height) => resolveStreams(
          videoId,
          maxHeightOverride: height,
          withCaptions: withCaptions,
          preferVp9: preferVp9,
          includeMetadata: includeMetadata,
          preferMuxed: preferMuxed,
          allowRelay: allowRelay,
        ),
      );
    }
    maxHeightOverride = maxHeightOverride.clamp(144, 1080);
    // Cobalt relay policy. Trailers and reels (no metadata, no captions) try
    // it first: it is what still works when YouTube bot-checks this device.
    // Full playback wants metadata, captions, quality switching and seeking,
    // which a tunnel lacks, so it only falls back to the relay when direct
    // extraction fails. `allowRelay: false` never relays (consumers that
    // need byte ranges); `true` forces relay-first.
    final relayFirst = allowRelay ?? (!includeMetadata && !withCaptions);
    final relayFallback = allowRelay != false;
    final key = _resolveKey(
      videoId,
      maxHeightOverride,
      withCaptions,
      preferVp9,
      includeMetadata,
      preferMuxed,
      relayFirst,
      relayFallback,
    );
    final cached = _resolveCache[key];
    if (cached != null && _cacheUsable(cached)) {
      return Future.value(cached.streams);
    }
    final inFlight = _resolveInFlight[key];
    if (inFlight != null) return inFlight;
    final generation = _resolveGeneration[videoId] ?? 0;
    final future = _resolutionQueue.run<YoutubeResolvedStreams?>(() {
      if (generation != (_resolveGeneration[videoId] ?? 0)) {
        return Future.value(null);
      }
      return _resolveUncached(
        videoId,
        maxHeightOverride: maxHeightOverride,
        withCaptions: withCaptions,
        preferVp9: preferVp9,
        includeMetadata: includeMetadata,
        preferMuxed: preferMuxed,
        relayFirst: relayFirst,
        relayFallback: relayFallback,
        cacheKey: key,
        generation: generation,
      );
    }, foreground: includeMetadata || withCaptions);
    _resolveInFlight[key] = future;
    // Block body: an arrow would return the removed (already-completed)
    // future for whenComplete to await — harmless here because the map holds
    // the INNER future, but one refactor from the self-deadlock this exact
    // shape caused in remote_control_state. Don't leave the trap armed.
    return future.whenComplete(() {
      if (identical(_resolveInFlight[key], future)) {
        _resolveInFlight.remove(key);
      }
    });
  }

  static String _resolveKey(
    String videoId,
    int? maxHeightOverride,
    bool withCaptions,
    bool preferVp9,
    bool includeMetadata,
    bool preferMuxed,
    bool relayFirst,
    bool relayFallback,
  ) {
    var base = maxHeightOverride == null
        ? videoId
        : '$videoId#h$maxHeightOverride';
    if (preferVp9) base = '$base#vp9';
    if (!includeMetadata) base = '$base#preview';
    if (preferMuxed) base = '$base#muxed';
    // A range-requiring consumer must never be handed a cached relay tunnel.
    if (relayFirst) base = '$base#relay';
    if (!relayFallback) base = '$base#norelay';
    return withCaptions ? '$base#cc' : base;
  }

  static Future<YoutubeResolvedStreams?> _resolveUncached(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool preferVp9 = false,
    bool includeMetadata = true,
    bool preferMuxed = false,
    bool relayFirst = false,
    bool relayFallback = false,
    required String cacheKey,
    required int generation,
  }) async {
    // Read the user's resolution cap on the MAIN isolate — SharedPreferences is
    // a platform channel and isn't available in the background isolate below.
    // An explicit override (ambient trailers) skips the pref entirely.
    final maxHeight =
        maxHeightOverride ?? await StorageService.getYoutubeMaxHeight();
    try {
      // youtube_explode fetches the watch page, deciphers the signature cipher
      // and parses a large player-response JSON — all synchronous CPU that would
      // otherwise freeze the UI isolate (blocking DPAD/focus) for ~1s per client
      // it tries. Run it in a throwaway background isolate so the main isolate
      // only awaits (the network calls are already async).
      final preferredClient = _preferredClient;
      final override = streamResolverOverride;
      // Relay order is decided by [resolveStreams]: previews try Cobalt
      // first, full playback only after direct extraction fails.
      // Test overrides never contact public endpoints.
      // Whether a relay miss is Cobalt's real answer about this video (every
      // instance refused it, or its relay already failed in a player) rather
      // than an instance being rate-limited or unreachable at that moment.
      var relayMissFinal = true;
      Future<CobaltMedia?> tryRelay() async {
        if (_relayBypassed(videoId)) return null;
        final relayOverride = cobaltResolverOverride;
        try {
          if (relayOverride != null) {
            return await relayOverride(videoId, maxHeight);
          }
          if (override != null) return null;
          final media = await CobaltService.instance.resolve(
            videoId,
            maxHeight: maxHeight,
          );
          if (media == null) {
            relayMissFinal = CobaltService.instance.knowsUnservable(videoId);
          }
          return media;
        } catch (e) {
          debugPrint('YoutubeService: relay failed for $videoId — $e');
          relayMissFinal = false;
          return null;
        }
      }

      ({YoutubeResolvedStreams streams, String client}) relayed(
        CobaltMedia relay,
      ) => (
        streams: YoutubeResolvedStreams(
          playUrl: relay.url,
          downloadUrl: relay.url,
          // Cobalt doesn't report actual dimensions: don't label the
          // requested resolution as a verified delivered resolution.
          // A tunnel can be (re)opened only until the instance's own
          // expiry; fall back to a conservative window without one.
          validUntil:
              relay.expiresAt ??
              DateTime.now().add(const Duration(seconds: 45)),
          isRelay: true,
        ),
        client: 'cobalt',
      );

      // When the relay can't serve a trailer or reel, fall back to the
      // original low-res path: one muxed (audio+video) MP4, usually 360p.
      // It is the stream YouTube still hands out most reliably, opens in
      // every player (AVFoundation included) and needs no audio pairing.
      final directMuxed = preferMuxed || relayFirst;
      Future<({YoutubeResolvedStreams streams, String client})?>
      direct() async {
        if (relayFirst) {
          debugPrint(
            'YoutubeService: $videoId low-res fallback '
            '${relayMissFinal ? '(every Cobalt instance refused it)' : '(Cobalt busy — retried on next request)'}',
          );
        }
        try {
          return override != null
              ? await override(
                  videoId,
                  maxHeight,
                  withCaptions,
                  preferVp9,
                  includeMetadata,
                  directMuxed,
                  preferredClient,
                )
              : await Isolate.run(
                  () => _resolveStreamsBlocking(
                    videoId,
                    maxHeight,
                    withCaptions,
                    preferVp9,
                    includeMetadata,
                    directMuxed,
                    preferredClient,
                  ),
                );
        } catch (e) {
          // Covers isolate-spawn failures and any error rethrown from the
          // extraction, so a YouTube cipher break is still diagnosable.
          debugPrint('YoutubeService: direct resolve failed for $videoId — $e');
          return null;
        }
      }

      ({YoutubeResolvedStreams streams, String client})? result;
      if (relayFirst) {
        final media = await tryRelay();
        if (media != null) result = relayed(media);
      }
      result ??= await direct();
      if (!relayFirst &&
          relayFallback &&
          !(result?.streams.hasPlayable ?? false)) {
        // YouTube bot-checked this device: the relay fetches from elsewhere.
        final media = await tryRelay();
        if (media != null) result = relayed(media);
      }
      final streams = result?.streams;
      if (streams != null && generation == (_resolveGeneration[videoId] ?? 0)) {
        if (streams.isRelay) {
          _relayUrlIds[streams.playUrl!] = videoId;
          while (_relayUrlIds.length > 128) {
            _relayUrlIds.remove(_relayUrlIds.keys.first);
          }
        } else if (result!.client != 'cobalt') {
          _preferredClient = result.client;
        }
        // Prune expired entries so the cache stays bounded to the active window.
        _resolveCache.removeWhere((_, e) => !_cacheUsable(e));
        // A low-res fallback taken only because Cobalt was momentarily out
        // of rotation is provisional: let the next request try Cobalt again.
        final provisional = relayFirst && !streams.isRelay && !relayMissFinal;
        _resolveCache[cacheKey] = _ResolvedCacheEntry(
          streams,
          DateTime.now(),
          until: provisional
              ? DateTime.now().add(const Duration(seconds: 60))
              : null,
        );
        while (_resolveCache.length > 64) {
          _resolveCache.remove(_resolveCache.keys.first);
        }
      }
      return streams;
    } catch (e) {
      // Covers both isolate-spawn failures and any error rethrown from the
      // extraction (the isolate lets errors propagate rather than swallowing
      // them) — so a YouTube cipher/player-response break is still diagnosable.
      debugPrint('YoutubeService: resolve failed for $videoId — $e');
      return null;
    }
  }

  /// The heavy resolution, run OFF the main isolate. Pure Dart (youtube_explode
  /// is HTTP-only, no plugins/platform channels), so it's isolate-safe. The
  /// [yt_explode.YoutubeExplode] instance (and any sockets) die with the isolate.
  /// A failed client rung is logged and the next one tried; only an unexpected
  /// error outside the ladder still propagates to [_resolveUncached]. Only
  /// [yt_explode.YoutubeExplode.close] is guarded so a teardown failure can't
  /// discard a valid result.
  static Future<({YoutubeResolvedStreams streams, String client})?>
  _resolveStreamsBlocking(
    String videoId,
    int maxHeight,
    bool withCaptions,
    bool preferVp9,
    bool includeMetadata,
    bool preferMuxed,
    String? preferredClient,
  ) async {
    var yt = yt_explode.YoutubeExplode(httpClient: YoutubePlaybackHttpClient());
    try {
      // Client ladder — impersonations of official YouTube apps, tried in
      // order until one yields URLs that actually answer. Every rung earns
      // its place:
      //  * androidVr first: its googlevideo URLs open directly in ffmpeg/mpv
      //    and need no PO token — but YouTube A/B-kills this client by region
      //    (since ~2026-03 affected regions intermittently get only format 18
      //    or URL-less streams), so it can't be the only rung.
      //  * androidSdkless second: the token-free android variant (omits
      //    androidSdkVersion, so YouTube's PO-token requirement never
      //    triggers). Android-family URLs can still 403 without a Range
      //    header — which media_kit's bundled ffmpeg omits on initial open —
      //    hence the probe below.
      //  * android last: sdkless's parent client, WITH the androidSdkVersion
      //    field that trips YouTube's PO-token gate for some regions. Mostly
      //    redundant, but A/B throttling is per-client, so it occasionally
      //    answers when both variants above are being squeezed — and when its
      //    URLs are token-gated the probe rejects them.
      // A web-family rung (tv/safari) would dodge the android quirks entirely
      // and is what yt-dlp defaults to — but in youtube_explode 3.1.0 those
      // clients' signed URLs need the deno-based JS challenge solver, which
      // can't ship on user devices. Probed live 2026-08: tv and safari yield
      // host-less URLs ("No host specified in URI"), mweb and mediaConnect
      // 403. Revisit only if the library gains an on-device solver.
      // youtube_explode HEAD-checks only the FIRST stream of each manifest,
      // which can pass while the adaptive streams we actually pick still 403 —
      // so a rung is accepted only after ITS chosen URLs survive the probe.
      final rungs = <(String, List<yt_explode.YoutubeApiClient>)>[
        ('androidVr', [yt_explode.YoutubeApiClient.androidVr]),
        ('androidSdkless', [yt_explode.YoutubeApiClient.androidSdkless]),
        ('android', [yt_explode.YoutubeApiClient.android]),
      ];
      // Reuse the last validated client first rather than paying for a known
      // failing client on every clip. The remaining clients stay as fallbacks.
      if (preferredClient != null) {
        final index = rungs.indexWhere((rung) => rung.$1 == preferredClient);
        if (index > 0) rungs.insert(0, rungs.removeAt(index));
      }
      var selectedClient = rungs.first.$1;
      _StreamSelection? selection;
      _StreamSelection? usableWithoutMuxedFallback;
      String? adaptiveClient;
      _StreamSelection? muxedOnlyFallback;
      String? muxedClient;
      _StreamSelection? lowerQualityFallback;
      String? lowerQualityClient;
      for (final (label, clients) in rungs) {
        yt_explode.StreamManifest manifest;
        try {
          manifest = await yt.videos.streamsClient
              .getManifest(
                videoId,
                ytClients: clients,
                // Skip a redundant watch-page fetch on the first attempt.
                // Remaining clients use the conservative extraction path.
                requireWatchPage: label != rungs.first.$1,
              )
              .timeout(const Duration(seconds: 5));
        } catch (e) {
          debugPrint('YoutubeService: $videoId [$label] manifest failed — $e');
          yt.close();
          yt = yt_explode.YoutubeExplode(
            httpClient: YoutubePlaybackHttpClient(),
          );
          continue;
        }
        final candidate = _selectStreams(
          manifest,
          maxHeight,
          preferVp9,
          preferMuxed,
        );
        if (candidate == null) {
          debugPrint(
            'YoutubeService: $videoId [$label] had no playable streams',
          );
          continue;
        }
        final usability = await _chosenUrlsUsable(
          candidate.playUrl,
          candidate.audioUrl,
          candidate.bestMuxedUrl,
        );
        if (!usability.primary &&
            usability.muxedFallback &&
            candidate.bestMuxedUrl != null) {
          final fallback = _StreamSelection(
            playUrl: candidate.bestMuxedUrl!,
            audioUrl: null,
            qualities: const [],
            bestMuxedUrl: candidate.bestMuxedUrl,
            bestMuxedHeight: candidate.bestMuxedHeight,
          );
          if (preferMuxed) {
            selection = fallback;
            selectedClient = label;
            break;
          }
          if (muxedOnlyFallback == null ||
              (fallback.playbackHeight ?? 0) >
                  (muxedOnlyFallback.playbackHeight ?? 0)) {
            muxedOnlyFallback = fallback;
            muxedClient = label;
          }
          continue;
        }
        if (!usability.primary) {
          debugPrint(
            'YoutubeService: $videoId [$label] chosen URLs returned 403',
          );
          continue;
        }
        // A download fallback is optional: don't fetch two more manifests
        // when the requested adaptive video and audio already work.
        if (!preferMuxed &&
            usability.primary &&
            (candidate.playbackHeight ?? 0) >= maxHeight) {
          selection = usability.muxedFallback
              ? candidate
              : candidate.withoutMuxedFallback();
          selectedClient = label;
          break;
        }
        if (!usability.muxedFallback) {
          // Keep the working adaptive pair as a last resort, but try the next
          // client for a muxed URL that single-URL players can actually open.
          if (usableWithoutMuxedFallback == null ||
              (candidate.playbackHeight ?? 0) >
                  (usableWithoutMuxedFallback.playbackHeight ?? 0)) {
            usableWithoutMuxedFallback = candidate.withoutMuxedFallback();
            adaptiveClient = label;
          }
          debugPrint(
            'YoutubeService: $videoId [$label] muxed fallback returned 403',
          );
          continue;
        }
        // Clients can expose a low-resolution muxed or adaptive subset, even for HD uploads.
        // A high-resolution caller must try the other clients before accepting
        // that low-resolution source. Keep it as a playable final fallback.
        if (!preferMuxed &&
            candidate.playbackHeight != null &&
            candidate.playbackHeight! < maxHeight) {
          if (lowerQualityFallback == null ||
              candidate.playbackHeight! >
                  (lowerQualityFallback.playbackHeight ?? 0)) {
            lowerQualityFallback = candidate;
            lowerQualityClient = label;
          }
          continue;
        }
        if (label != 'androidVr') {
          // The line that matters in a user's log: which fallback saved this.
          debugPrint('YoutubeService: $videoId resolved via [$label]');
        }
        selection = candidate;
        selectedClient = label;
        break;
      }
      if (selection == null) {
        final fallbacks =
            <(_StreamSelection, String)>[
              if (lowerQualityFallback != null)
                (lowerQualityFallback, lowerQualityClient!),
              if (usableWithoutMuxedFallback != null)
                (usableWithoutMuxedFallback, adaptiveClient!),
              if (muxedOnlyFallback != null) (muxedOnlyFallback, muxedClient!),
            ]..sort(
              (a, b) => (b.$1.playbackHeight ?? 0).compareTo(
                a.$1.playbackHeight ?? 0,
              ),
            );
        if (fallbacks.isNotEmpty) {
          selection = fallbacks.first.$1;
          selectedClient = fallbacks.first.$2;
        }
      }
      if (selection == null) {
        debugPrint('YoutubeService: $videoId — every client rung failed');
        return null;
      }
      final playUrl = selection.playUrl;
      final audioUrl = selection.audioUrl;
      final qualities = selection.qualities;
      final bestMuxed = selection.bestMuxedUrl;
      final bestMuxedHeight = selection.bestMuxedHeight;

      String? title;
      String? thumb;
      int? duration;
      // Metadata and the caption manifest are independent network calls; run
      // them concurrently so captions (off by default, consumed lazily from the
      // menu) don't serialize extra latency onto the play path. Both are
      // best-effort — neither can block or fail playback.
      final captions = <YoutubeCaptionTrack>[];
      await Future.wait([
        () async {
          if (!includeMetadata) return;
          try {
            final video = await yt.videos
                .get(videoId)
                .timeout(const Duration(seconds: 3));
            title = video.title;
            thumb = video.thumbnails.highResUrl;
            duration = video.duration?.inSeconds;
          } catch (_) {
            // Metadata is best-effort; the stream URL is what matters.
          }
        }(),
        () async {
          if (!withCaptions) return;
          // Request VTT only so each language yields a single direct WebVTT URL
          // the player can feed to its existing external-subtitle pipeline.
          try {
            final ccManifest = await yt.videos.closedCaptions
                .getManifest(
                  videoId,
                  formats: const [yt_explode.ClosedCaptionFormat.vtt],
                )
                .timeout(const Duration(seconds: 3));
            for (final t in ccManifest.tracks) {
              captions.add(
                YoutubeCaptionTrack(
                  url: t.url.toString(),
                  langCode: t.language.code,
                  langName: t.language.name.isNotEmpty
                      ? t.language.name
                      : t.language.code,
                  isAutoGenerated: t.isAutoGenerated,
                ),
              );
            }
          } catch (_) {
            // No captions available (or fetch failed) — leave the list empty.
          }
        }(),
      ]);

      // Describe the download stream for the user. Normally the muxed stream
      // (has audio, ≤720p). Only when no muxed stream exists do we fall back to
      // the video-only [playUrl] — a silent file whose height is its quality.
      final downloadUrl = bestMuxed ?? playUrl;
      int? downloadHeight;
      bool downloadHasAudio;
      if (bestMuxed != null) {
        downloadHeight = bestMuxedHeight;
        downloadHasAudio = true;
      } else {
        downloadHasAudio = false;
        final match = qualities.where((q) => q.videoUrl == playUrl);
        downloadHeight = match.isNotEmpty ? match.first.height : null;
      }

      return (
        client: selectedClient,
        streams: YoutubeResolvedStreams(
          playUrl: playUrl,
          audioUrl: audioUrl,
          downloadUrl: downloadUrl,
          downloadHeight: downloadHeight,
          downloadHasAudio: downloadHasAudio,
          title: title,
          thumbnailUrl: thumb,
          durationSeconds: duration,
          qualities: qualities,
          captions: captions,
        ),
      );
    } finally {
      // Guarded: a close() failure must not replace a valid return value (or a
      // legitimately-propagating extraction error) with a teardown exception.
      try {
        yt.close();
      } catch (_) {}
    }
  }

  /// Pick what one client's [manifest] has to offer: the default video-only
  /// + AAC audio pair, the quality-switcher list, and the best muxed
  /// single-file stream. Null when the manifest has nothing playable at all.
  static _StreamSelection? _selectStreams(
    yt_explode.StreamManifest manifest,
    int maxHeight,
    bool preferVp9,
    bool preferMuxed,
  ) {
    // Best muxed single-file stream (download + playback fallback). Keep the
    // stream object (not just its URL) so we can report its resolution as the
    // actual download quality to the user.
    final muxed =
        manifest.muxed.where((s) => s.videoResolution.height <= 1080).toList()
          ..sort(
            (a, b) =>
                b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
          );
    final muxedMp4 = muxed.where(
      (s) => s.container.name.toLowerCase() == 'mp4',
    );
    final cappedMuxed = muxedMp4.where(
      (s) => s.videoResolution.height <= maxHeight,
    );
    final bestMuxedStream = preferMuxed && cappedMuxed.isNotEmpty
        ? cappedMuxed.first
        : muxedMp4.isNotEmpty
        ? muxedMp4.first
        : (muxed.isNotEmpty ? muxed.first : null);
    final bestMuxed = bestMuxedStream?.url.toString();
    final bestMuxedHeight = bestMuxedStream?.videoResolution.height;

    // Use adaptive H.264/VP9 plus AAC, capped at 1080p. AV1 remains
    // excluded because decoder support varies across the player matrix.
    bool isAvc(String c) => c.toLowerCase().contains('avc');
    bool isVp9(String c) {
      final l = c.toLowerCase();
      return l.contains('vp9') || l.contains('vp09');
    }

    String? playUrl;
    String? audioUrl;
    final qualities = <YoutubeQuality>[];
    final videoOnly = manifest.videoOnly
        .where(
          (s) =>
              s.videoResolution.height <= 1080 &&
              (isAvc(s.videoCodec) || isVp9(s.videoCodec)),
        )
        .toList();
    final audioStreams = manifest.audioOnly
        .where((s) => s.container.name.toLowerCase() == 'mp4')
        .toList();
    if (videoOnly.isNotEmpty && audioStreams.isNotEmpty) {
      // Highest first; within a single height the tie-break is the caller's
      // call. Content playback keeps H.264 so the <=1080p rungs resolve to
      // the exact stream they used before VP9 was allowed (the risk-
      // containment contract above). Ambient trailers pass [preferVp9]:
      // YouTube serves VP9 at every rung, its encodes run visibly cleaner
      // at trailer bitrates, and every ambient surface's decoder handles it
      // (phone/desktop hardware VP9; Apple TV software VP9 at its 1080 cap;
      // Android TV certifies VP9 hardware decode for the Exo underlay).
      videoOnly.sort((a, b) {
        final byHeight = b.videoResolution.height.compareTo(
          a.videoResolution.height,
        );
        if (byHeight != 0) return byHeight;
        final aPreferred = preferVp9
            ? isVp9(a.videoCodec)
            : isAvc(a.videoCodec);
        final bPreferred = preferVp9
            ? isVp9(b.videoCodec)
            : isAvc(b.videoCodec);
        if (aPreferred == bPreferred) return 0;
        return aPreferred ? -1 : 1;
      });

      // One switchable entry per distinct height (highest first). Dedup keeps
      // the first, which — after the sort above — is H.264 wherever it exists.
      // The list is NOT filtered to maxHeight; the whole point of in-player
      // switching is to override the launch cap. YouTube can list several
      // bitrates per height; keep the first.
      final seenHeights = <int>{};
      for (final s in videoOnly) {
        final h = s.videoResolution.height;
        if (!seenHeights.add(h)) continue;
        qualities.add(YoutubeQuality(height: h, videoUrl: s.url.toString()));
      }

      // Select within the preference; all switchable qualities stay <=1080p.
      final atOrBelow = qualities.where((q) => q.height <= maxHeight).toList();
      playUrl =
          (atOrBelow.isNotEmpty ? atOrBelow.first : qualities.last).videoUrl;

      audioStreams.sort(
        (a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
      );
      audioUrl = audioStreams.first.url.toString();
    }

    // A single connection starts the native iOS preview without waiting for
    // independent audio/video requests. Keep adaptive qualities for full player.
    if (preferMuxed && bestMuxed != null) {
      playUrl = bestMuxed;
      audioUrl = null;
      qualities.clear();
    }
    // Fall back to muxed if adaptive streams are unavailable.
    if (playUrl == null) {
      playUrl = bestMuxed;
      audioUrl = null;
    }
    if (playUrl == null) return null;
    return _StreamSelection(
      playUrl: playUrl,
      audioUrl: audioUrl,
      qualities: qualities,
      bestMuxedUrl: bestMuxed,
      bestMuxedHeight: bestMuxedHeight,
    );
  }

  /// Probe the selected connections concurrently. Reject explicit HTTP errors;
  /// a short, inconclusive transport probe must not prevent player retries.
  static Future<({bool primary, bool muxedFallback})> _chosenUrlsUsable(
    String playUrl,
    String? audioUrl,
    String? muxedFallbackUrl,
  ) async {
    Future<bool> usable(String url) async {
      final uri = Uri.tryParse(url);
      if (uri == null ||
          uri.host.isEmpty ||
          (uri.scheme != 'https' && uri.scheme != 'http')) {
        return false;
      }
      try {
        final resp = await probeYoutubeStream(uri);
        return resp.statusCode >= 200 && resp.statusCode < 400;
      } catch (_) {
        // A transport timeout is inconclusive. The player can still try it;
        // an explicit HTTP denial above is never treated as success.
        return true;
      }
    }

    final primaryCheck = Future.wait([
      usable(playUrl),
      if (audioUrl != null && audioUrl.isNotEmpty) usable(audioUrl),
    ]).then((checks) => !checks.contains(false));
    final fallbackCheck =
        muxedFallbackUrl != null &&
            muxedFallbackUrl.isNotEmpty &&
            muxedFallbackUrl != playUrl
        ? usable(muxedFallbackUrl)
        : Future<bool>.value(
            muxedFallbackUrl == playUrl || muxedFallbackUrl == null,
          );
    final checks = await Future.wait([primaryCheck, fallbackCheck]);
    return (
      primary: checks[0],
      muxedFallback: muxedFallbackUrl == playUrl ? checks[0] : checks[1],
    );
  }

  // ============== URL helpers (shared with Lemmy) ==============

  static final List<RegExp> _idPatterns = [
    RegExp(r'[?&]v=([a-zA-Z0-9_-]{11})'),
    RegExp(r'youtu\.be/([a-zA-Z0-9_-]{11})'),
    RegExp(r'/shorts/([a-zA-Z0-9_-]{11})'),
    RegExp(r'/embed/([a-zA-Z0-9_-]{11})'),
    RegExp(r'/live/([a-zA-Z0-9_-]{11})'),
  ];

  /// Extract a YouTube video id from any common YouTube URL form.
  static String? extractYouTubeId(String url) {
    if (url.isEmpty) return null;
    for (final pattern in _idPatterns) {
      final match = pattern.firstMatch(url);
      if (match != null) return match.group(1);
    }
    return null;
  }

  /// Whether a URL points to YouTube.
  static bool isYouTubeUrl(String url) {
    final lower = url.toLowerCase();
    return lower.contains('youtube.com') || lower.contains('youtu.be');
  }

  /// A YouTube-hosted thumbnail for a video id.
  static String thumbnailForId(String videoId) =>
      'https://i.ytimg.com/vi/$videoId/hqdefault.jpg';
}
